trigger:
- main  # Adjust this to your preferred branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_CLOUD_API_TOKEN: $(TF_CLOUD_API_TOKEN)  # From variable group
  WORKSPACE_NAME: $(WORKSPACE_NAME)            # From variable group
  TF_CLOUD_ORG: $(TF_CLOUD_ORG)                # From variable group

steps:
- script: |
    echo "Triggering Terraform Cloud run..."
    curl \
      --header "Authorization: Bearer $(TF_CLOUD_API_TOKEN)" \
      --header "Content-Type: application/vnd.api+json" \
      --request POST \
      --data '{
        "data": {
          "attributes": {
            "is-destroy": false
          },
          "type": "runs",
          "relationships": {
            "workspace": {
              "data": {
                "type": "workspaces",
                "id": "$(TF_CLOUD_ORG)/$(WORKSPACE_NAME)"
              }
            }
          }
        }
      }' \
      https://app.terraform.io/api/v2/runs
  displayName: 'Trigger Terraform Cloud Run'
