trigger:
- main  # Change this to your branch if needed

pool:
  name: self  # Replace with your actual self-hosted agent pool name

variables:
  TF_CLOUD_API_TOKEN: $(TF_CLOUD_API_TOKEN)  # From variable group
  WORKSPACE_NAME: $(WORKSPACE_NAME)            # From variable group
  TF_CLOUD_ORG: $(TF_CLOUD_ORG)                # From variable group

stages:
- stage: TriggerTerraformCloud
  jobs:
  - job: TriggerRun
    displayName: 'Trigger Terraform Cloud Run'
    pool:
      name: 'YourSelfHostedAgentPool'  # Ensure this is your self-hosted pool
    steps:
    - checkout: self

    - script: |
        echo "Triggering Terraform Cloud run..."
        
        # Prepare the JSON data for the API request
        setlocal enabledelayedexpansion
        set "data={
          \"data\": {
            \"attributes\": {
              \"is-destroy\": false
            },
            \"type\": \"runs\",
            \"relationships\": {
              \"workspace\": {
                \"data\": {
                  \"type\": \"workspaces\",
                  \"id\": \"$(TF_CLOUD_ORG)/$(WORKSPACE_NAME)\"
                }
              }
            }
          }
        }"

        # Make the API request
        response=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
          --header "Authorization: Bearer $(TF_CLOUD_API_TOKEN)" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data "!data!" \
          https://app.terraform.io/api/v2/runs)

        # Separate the body and the status
        body=$(echo "$response" | sed 's/HTTPSTATUS:[0-9]*$//')
        status=$(echo "$response" | grep -o 'HTTPSTATUS:[0-9]*$' | sed 's/HTTPSTATUS://')

        echo "Response Body: $body"
        echo "Response Status: $status"

        # Check if the request was successful
        if [ "$status" -ne 200 ]; then
          echo "Error triggering Terraform Cloud run!"
          exit 1
        fi
      displayName: 'Trigger Terraform Cloud Run'
