trigger:
  branches:
    include:
      - main  # Change to your desired branch

pool:
  name: self  # Replace with your self-hosted agent pool name

steps:
  - script: |
      echo "Installing Terraform..."
      curl -LO https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
      unzip terraform_$(terraformVersion)_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - script: |
      echo "Logging in to Docker..."
      echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
    displayName: 'Docker Login'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)  # Set this as a secret variable in Azure DevOps
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)  # Set this as a secret variable in Azure DevOps

  - script: |
      echo "Initializing Terraform..."
      terraform init

      echo "Planning Terraform..."
      terraform plan -out=tfplan

      echo "Applying Terraform..."
      terraform apply -auto-approve tfplan
    displayName: 'Run Terraform'

  - script: |
      echo "Building Docker Image..."
      docker build -t your-image-name:latest .
    displayName: 'Build Docker Image'

  - script: |
      echo "Pushing Docker Image to Registry..."
      docker push your-image-name:latest
    displayName: 'Push Docker Image'
