trigger:
  branches:
    include:
      - main  # Adjust to your main branch name

pool:
  name: Agent1  # Replace with the name of your self-hosted agent pool

steps:
  - checkout: self  # Ensure the repository is checked out

  - script: |
      echo "Listing root directory contents..."
      dir C:\agents\_work\1\s  # List files in the root directory
    displayName: 'List Root Directory'

  - script: |
      echo "Listing Terraform directory contents..."
      cd terraform  # Change to your Terraform directory
      dir  # Use dir for Windows
    displayName: 'List Terraform Directory'

  - script: |
      echo "Installing Terraform..."
      curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_windows_amd64.zip
      unzip terraform_1.5.0_windows_amd64.zip
      move terraform.exe C:\Windows\System32\
      terraform --version
    displayName: 'Install Terraform'

  - script: |
      echo "Initializing Terraform..."
      cd terraform  # Change to your Terraform directory
      terraform init
    displayName: 'Terraform Init'

  - script: |
      echo "Applying Terraform Configuration..."
      cd terraform  # Ensure you are in the correct directory
      terraform apply -auto-approve
    displayName: 'Terraform Apply'

  - script: |
      echo "Building Docker Image..."
      cd docker  # Change to your Dockerfile directory
      docker build -t my-docker-image:latest .
    displayName: 'Build Docker Image'
