trigger:
- main  # Change this to your branch if needed

pool:
  name: self  # Replace with your actual self-hosted agent pool name

variables:
  TF_CLOUD_API_TOKEN: ARQKMRBLwfbVKw.atlasv1.NdLzUuk49HHqHYfIHMfkKl7GiGXbuyyxszGPNPqgfhOTzGADwn859iKcHYlDW1vVSMA
  WORKSPACE_NAME: Azure_TerraformDockerPipeline
  TF_CLOUD_ORG: Demo_ME

stages:
- stage: TriggerTerraformCloud
  jobs:
  - job: TriggerRun
    displayName: 'Trigger Terraform Cloud Run'
    pool:
      name: self  # Ensure this is your self-hosted pool
    steps:
    - checkout: self

    - powershell: |
        # Debugging output to check environment variables
        Write-Host "TF_CLOUD_ORG: $env:TF_CLOUD_ORG"
        Write-Host "WORKSPACE_NAME: $env:WORKSPACE_NAME"

        $data = @{
          data = @{
            attributes = @{
              "is-destroy" = $false
            }
            type = "runs"
            relationships = @{
              workspace = @{
                data = @{
                  type = "workspaces"
                  id = "$env:TF_CLOUD_ORG/$env:WORKSPACE_NAME"
                }
              }
            }
          }
        }

        $jsonData = $data | ConvertTo-Json -Depth 10

        $response = Invoke-RestMethod -Uri 'https://app.terraform.io/api/v2/runs' `
            -Method Post `
            -Headers @{
              "Authorization" = "Bearer $env:TF_CLOUD_API_TOKEN"
              "Content-Type" = "application/vnd.api+json"
            } `
            -Body $jsonData

        Write-Host "Response: $($response | ConvertTo-Json -Depth 10)"
      displayName: 'Trigger Terraform Cloud Run'
