trigger:
  branches:
    include:
      - main  # Adjust to your main branch name

pool:
  name: ram  # Replace with the name of your self-hosted agent pool

steps:
  - script: |
      echo "Installing Terraform..."
      curl -LO https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      unzip terraform_1.5.0_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - script: |
      echo "Initializing Terraform..."
      cd terraform  # Change to your Terraform directory
      terraform init
    displayName: 'Terraform Init'

  - script: |
      echo "Applying Terraform Configuration..."
      terraform apply -auto-approve
    displayName: 'Terraform Apply'

  - script: |
      echo "Building Docker Image..."
      cd docker  # Change to your Dockerfile directory
      docker build -t my-docker-image:latest .
    displayName: 'Build Docker Image'
